// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    var updateDisplay;
    updateDisplay = function(data) {
      var displayedVal, li, name, ul, val, _results;
      ul = $("#features");
      ul.empty();
      _results = [];
      for (name in data) {
        val = data[name];
        displayedVal = val ? "on" : "off";
        li = $("<li>", {
          html: "" + name + ": <span class='on'>" + displayedVal + "</span> <a href='#' class='toggle'>Toggle</a>"
        });
        li.data("feature-name", name);
        li.data("feature-enabled", val);
        _results.push(ul.append(li));
      }
      return _results;
    };
    $("#container").delegate(".toggle", "click", function(e) {
      var li, name, newVal, payload;
      e.preventDefault();
      li = $(this).parent();
      name = li.data("feature-name");
      newVal = !li.data("feature-enabled");
      payload = {};
      payload[name] = newVal;
      return $.post("/features.json", payload, updateDisplay);
    });
    return $.getJSON("/features.json", updateDisplay);
  });

}).call(this);
